#CLK,RST
set_property PACKAGE_PIN N13 [get_ports C_SYS_CLK_I]
set_property IOSTANDARD LVCMOS33 [get_ports C_SYS_CLK_I]

set_property PACKAGE_PIN P1 [get_ports C_SYS_RST_I]
set_property IOSTANDARD LVCMOS33 [get_ports C_SYS_RST_I]


set_property IOSTANDARD LVCMOS33 [get_ports S_DACREFCLK1_I]
set_property PACKAGE_PIN C11 [get_ports S_DACREFCLK1_I]

set_property IOSTANDARD LVCMOS33 [get_ports S_DACREFCLK2_I]
set_property PACKAGE_PIN E12 [get_ports S_DACREFCLK2_I]


#LED
set_property PACKAGE_PIN M4 [get_ports LED_O]

set_property IOSTANDARD LVCMOS33 [get_ports LED_O]

#DAC1
set_property PACKAGE_PIN B10 [get_ports {S_DAC1_O[0]}]
set_property PACKAGE_PIN B11 [get_ports {S_DAC1_O[1]}]
set_property PACKAGE_PIN B12 [get_ports {S_DAC1_O[2]}]
set_property PACKAGE_PIN A12 [get_ports {S_DAC1_O[3]}]
set_property PACKAGE_PIN D8 [get_ports {S_DAC1_O[4]}]
set_property PACKAGE_PIN D9 [get_ports {S_DAC1_O[5]}]
set_property PACKAGE_PIN A13 [get_ports {S_DAC1_O[6]}]
set_property PACKAGE_PIN A14 [get_ports {S_DAC1_O[7]}]
set_property PACKAGE_PIN D10 [get_ports {S_DAC1_O[8]}]
set_property PACKAGE_PIN B14 [get_ports {S_DAC1_O[9]}]
set_property PACKAGE_PIN C14 [get_ports {S_DAC1_O[10]}]
set_property PACKAGE_PIN A15 [get_ports {S_DAC1_O[11]}]
set_property PACKAGE_PIN B15 [get_ports {S_DAC1_O[12]}]
set_property PACKAGE_PIN C8 [get_ports {S_DAC1_O[13]}]
set_property PACKAGE_PIN A10 [get_ports S_DAC1_REFCLK_O]

set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC1_O[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC1_O[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC1_O[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC1_O[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC1_O[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC1_O[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC1_O[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC1_O[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC1_O[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC1_O[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC1_O[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC1_O[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC1_O[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC1_O[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports S_DAC1_REFCLK_O]


set_property DRIVE 12[get_ports {S_DAC1_O[13]}]
set_property DRIVE 12[get_ports {S_DAC1_O[12]}]
set_property DRIVE 12[get_ports {S_DAC1_O[11]}]
set_property DRIVE 12[get_ports {S_DAC1_O[10]}]
set_property DRIVE 12[get_ports {S_DAC1_O[9]}]
set_property DRIVE 12[get_ports {S_DAC1_O[8]}]
set_property DRIVE 12[get_ports {S_DAC1_O[7]}]
set_property DRIVE 12[get_ports {S_DAC1_O[6]}]
set_property DRIVE 12[get_ports {S_DAC1_O[5]}]
set_property DRIVE 12[get_ports {S_DAC1_O[4]}]
set_property DRIVE 12[get_ports {S_DAC1_O[3]}]
set_property DRIVE 12[get_ports {S_DAC1_O[2]}]
set_property DRIVE 12[get_ports {S_DAC1_O[1]}]
set_property DRIVE 12[get_ports {S_DAC1_O[0]}]
set_property DRIVE 12[get_ports S_DAC1_REFCLK_O]

set_property PULLUP true [get_ports {S_DAC1_O[13]}]
set_property PULLUP true [get_ports {S_DAC1_O[12]}]
set_property PULLUP true [get_ports {S_DAC1_O[11]}]
set_property PULLUP true [get_ports {S_DAC1_O[10]}]
set_property PULLUP true [get_ports {S_DAC1_O[9]}]
set_property PULLUP true [get_ports {S_DAC1_O[8]}]
set_property PULLUP true [get_ports {S_DAC1_O[7]}]
set_property PULLUP true [get_ports {S_DAC1_O[6]}]
set_property PULLUP true [get_ports {S_DAC1_O[5]}]
set_property PULLUP true [get_ports {S_DAC1_O[4]}]
set_property PULLUP true [get_ports {S_DAC1_O[3]}]
set_property PULLUP true [get_ports {S_DAC1_O[2]}]
set_property PULLUP true [get_ports {S_DAC1_O[1]}]
set_property PULLUP true [get_ports {S_DAC1_O[0]}]
set_property PULLUP true [get_ports S_DAC1_REFCLK_O]
#DAC2

set_property PACKAGE_PIN D11 [get_ports {S_DAC2_O[0]}]
set_property PACKAGE_PIN E11 [get_ports {S_DAC2_O[1]}]
set_property PACKAGE_PIN B16 [get_ports {S_DAC2_O[2]}]
set_property PACKAGE_PIN C16 [get_ports {S_DAC2_O[3]}]
set_property PACKAGE_PIN C13 [get_ports {S_DAC2_O[4]}]
set_property PACKAGE_PIN E13 [get_ports {S_DAC2_O[5]}]
set_property PACKAGE_PIN D14 [get_ports {S_DAC2_O[6]}]
set_property PACKAGE_PIN D15 [get_ports {S_DAC2_O[7]}]
set_property PACKAGE_PIN F12 [get_ports {S_DAC2_O[8]}]
set_property PACKAGE_PIN F13 [get_ports {S_DAC2_O[9]}]
set_property PACKAGE_PIN D16 [get_ports {S_DAC2_O[10]}]
set_property PACKAGE_PIN E16 [get_ports {S_DAC2_O[11]}]
set_property PACKAGE_PIN G12 [get_ports {S_DAC2_O[12]}]
set_property PACKAGE_PIN G11 [get_ports {S_DAC2_O[13]}]
set_property PACKAGE_PIN C9 [get_ports S_DAC2_REFCLK_O]

set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC2_O[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC2_O[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC2_O[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC2_O[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC2_O[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC2_O[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC2_O[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC2_O[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC2_O[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC2_O[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC2_O[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC2_O[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC2_O[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC2_O[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports S_DAC2_REFCLK_O]

set_property DRIVE 12[get_ports {S_DAC2_O[13]}]
set_property DRIVE 12[get_ports {S_DAC2_O[12]}]
set_property DRIVE 12[get_ports {S_DAC2_O[11]}]
set_property DRIVE 12[get_ports {S_DAC2_O[10]}]
set_property DRIVE 12[get_ports {S_DAC2_O[9]}]
set_property DRIVE 12[get_ports {S_DAC2_O[8]}]
set_property DRIVE 12[get_ports {S_DAC2_O[7]}]
set_property DRIVE 12[get_ports {S_DAC2_O[6]}]
set_property DRIVE 12[get_ports {S_DAC2_O[5]}]
set_property DRIVE 12[get_ports {S_DAC2_O[4]}]
set_property DRIVE 12[get_ports {S_DAC2_O[3]}]
set_property DRIVE 12[get_ports {S_DAC2_O[2]}]
set_property DRIVE 12[get_ports {S_DAC2_O[1]}]
set_property DRIVE 12[get_ports {S_DAC2_O[0]}]
set_property DRIVE 12[get_ports S_DAC2_REFCLK_O]

set_property PULLUP true [get_ports {S_DAC2_O[13]}]
set_property PULLUP true [get_ports {S_DAC2_O[12]}]
set_property PULLUP true [get_ports {S_DAC2_O[11]}]
set_property PULLUP true [get_ports {S_DAC2_O[10]}]
set_property PULLUP true [get_ports {S_DAC2_O[9]}]
set_property PULLUP true [get_ports {S_DAC2_O[8]}]
set_property PULLUP true [get_ports {S_DAC2_O[7]}]
set_property PULLUP true [get_ports {S_DAC2_O[6]}]
set_property PULLUP true [get_ports {S_DAC2_O[5]}]
set_property PULLUP true [get_ports {S_DAC2_O[4]}]
set_property PULLUP true [get_ports {S_DAC2_O[3]}]
set_property PULLUP true [get_ports {S_DAC2_O[2]}]
set_property PULLUP true [get_ports {S_DAC2_O[1]}]
set_property PULLUP true [get_ports {S_DAC2_O[0]}]
set_property PULLUP true [get_ports S_DAC2_REFCLK_O]
#DAC3

set_property PACKAGE_PIN E15 [get_ports {S_DAC3_O[0]}]
set_property PACKAGE_PIN F15 [get_ports {S_DAC3_O[1]}]
set_property PACKAGE_PIN H12 [get_ports {S_DAC3_O[2]}]
set_property PACKAGE_PIN H13 [get_ports {S_DAC3_O[3]}]
set_property PACKAGE_PIN H14 [get_ports {S_DAC3_O[4]}]
set_property PACKAGE_PIN G15 [get_ports {S_DAC3_O[5]}]
set_property PACKAGE_PIN F14 [get_ports {S_DAC3_O[6]}]
set_property PACKAGE_PIN G14 [get_ports {S_DAC3_O[7]}]
set_property PACKAGE_PIN G16 [get_ports {S_DAC3_O[8]}]
set_property PACKAGE_PIN H16 [get_ports {S_DAC3_O[9]}]
set_property PACKAGE_PIN J15 [get_ports {S_DAC3_O[10]}]
set_property PACKAGE_PIN J16 [get_ports {S_DAC3_O[11]}]
set_property PACKAGE_PIN K12 [get_ports {S_DAC3_O[12]}]
set_property PACKAGE_PIN M16 [get_ports {S_DAC3_O[13]}]
set_property PACKAGE_PIN H11 [get_ports S_DAC3_REFCLK_O]

set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC3_O[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC3_O[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC3_O[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC3_O[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC3_O[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC3_O[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC3_O[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC3_O[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC3_O[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC3_O[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC3_O[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC3_O[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC3_O[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC3_O[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports S_DAC3_REFCLK_O]

set_property DRIVE 12[get_ports {S_DAC3_O[13]}]
set_property DRIVE 12[get_ports {S_DAC3_O[12]}]
set_property DRIVE 12[get_ports {S_DAC3_O[11]}]
set_property DRIVE 12[get_ports {S_DAC3_O[10]}]
set_property DRIVE 12[get_ports {S_DAC3_O[9]}]
set_property DRIVE 12[get_ports {S_DAC3_O[8]}]
set_property DRIVE 12[get_ports {S_DAC3_O[7]}]
set_property DRIVE 12[get_ports {S_DAC3_O[6]}]
set_property DRIVE 12[get_ports {S_DAC3_O[5]}]
set_property DRIVE 12[get_ports {S_DAC3_O[4]}]
set_property DRIVE 12[get_ports {S_DAC3_O[3]}]
set_property DRIVE 12[get_ports {S_DAC3_O[2]}]
set_property DRIVE 12[get_ports {S_DAC3_O[1]}]
set_property DRIVE 12[get_ports {S_DAC3_O[0]}]
set_property DRIVE 12[get_ports S_DAC3_REFCLK_O]

set_property PULLUP true [get_ports {S_DAC3_O[13]}]
set_property PULLUP true [get_ports {S_DAC3_O[12]}]
set_property PULLUP true [get_ports {S_DAC3_O[11]}]
set_property PULLUP true [get_ports {S_DAC3_O[10]}]
set_property PULLUP true [get_ports {S_DAC3_O[9]}]
set_property PULLUP true [get_ports {S_DAC3_O[8]}]
set_property PULLUP true [get_ports {S_DAC3_O[7]}]
set_property PULLUP true [get_ports {S_DAC3_O[6]}]
set_property PULLUP true [get_ports {S_DAC3_O[5]}]
set_property PULLUP true [get_ports {S_DAC3_O[4]}]
set_property PULLUP true [get_ports {S_DAC3_O[3]}]
set_property PULLUP true [get_ports {S_DAC3_O[2]}]
set_property PULLUP true [get_ports {S_DAC3_O[1]}]
set_property PULLUP true [get_ports {S_DAC3_O[0]}]
set_property PULLUP true [get_ports S_DAC3_REFCLK_O]
#DAC4

set_property PACKAGE_PIN M14 [get_ports {S_DAC4_O[0]}]
set_property PACKAGE_PIN N16 [get_ports {S_DAC4_O[1]}]
set_property PACKAGE_PIN P16 [get_ports {S_DAC4_O[2]}]
set_property PACKAGE_PIN P15 [get_ports {S_DAC4_O[3]}]
set_property PACKAGE_PIN R15 [get_ports {S_DAC4_O[4]}]
set_property PACKAGE_PIN R16 [get_ports {S_DAC4_O[5]}]
set_property PACKAGE_PIN K13 [get_ports {S_DAC4_O[6]}]
set_property PACKAGE_PIN L13 [get_ports {S_DAC4_O[7]}]
set_property PACKAGE_PIN M12 [get_ports {S_DAC4_O[8]}]
set_property PACKAGE_PIN L15 [get_ports {S_DAC4_O[9]}]
set_property PACKAGE_PIN T15 [get_ports {S_DAC4_O[10]}]
set_property PACKAGE_PIN T14 [get_ports {S_DAC4_O[11]}]
set_property PACKAGE_PIN L14 [get_ports {S_DAC4_O[12]}]
set_property PACKAGE_PIN P14 [get_ports {S_DAC4_O[13]}]
set_property PACKAGE_PIN M15 [get_ports S_DAC4_REFCLK_O]

set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC4_O[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC4_O[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC4_O[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC4_O[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC4_O[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC4_O[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC4_O[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC4_O[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC4_O[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC4_O[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC4_O[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC4_O[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC4_O[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {S_DAC4_O[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports S_DAC4_REFCLK_O]

set_property DRIVE 12[get_ports {S_DAC4_O[13]}]
set_property DRIVE 12[get_ports {S_DAC4_O[12]}]
set_property DRIVE 12[get_ports {S_DAC4_O[11]}]
set_property DRIVE 12[get_ports {S_DAC4_O[10]}]
set_property DRIVE 12[get_ports {S_DAC4_O[9]}]
set_property DRIVE 12[get_ports {S_DAC4_O[8]}]
set_property DRIVE 12[get_ports {S_DAC4_O[7]}]
set_property DRIVE 12[get_ports {S_DAC4_O[6]}]
set_property DRIVE 12[get_ports {S_DAC4_O[5]}]
set_property DRIVE 12[get_ports {S_DAC4_O[4]}]
set_property DRIVE 12[get_ports {S_DAC4_O[3]}]
set_property DRIVE 12[get_ports {S_DAC4_O[2]}]
set_property DRIVE 12[get_ports {S_DAC4_O[1]}]
set_property DRIVE 12[get_ports {S_DAC4_O[0]}]
set_property DRIVE 12[get_ports S_DAC4_REFCLK_O]

set_property PULLUP true [get_ports {S_DAC4_O[13]}]
set_property PULLUP true [get_ports {S_DAC4_O[12]}]
set_property PULLUP true [get_ports {S_DAC4_O[11]}]
set_property PULLUP true [get_ports {S_DAC4_O[10]}]
set_property PULLUP true [get_ports {S_DAC4_O[9]}]
set_property PULLUP true [get_ports {S_DAC4_O[8]}]
set_property PULLUP true [get_ports {S_DAC4_O[7]}]
set_property PULLUP true [get_ports {S_DAC4_O[6]}]
set_property PULLUP true [get_ports {S_DAC4_O[5]}]
set_property PULLUP true [get_ports {S_DAC4_O[4]}]
set_property PULLUP true [get_ports {S_DAC4_O[3]}]
set_property PULLUP true [get_ports {S_DAC4_O[2]}]
set_property PULLUP true [get_ports {S_DAC4_O[1]}]
set_property PULLUP true [get_ports {S_DAC4_O[0]}]
set_property PULLUP true [get_ports S_DAC4_REFCLK_O]
#IO_IIC


#LCD


#IIC MUX--deprecated




#IO

set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_io[0]}]
set_property PACKAGE_PIN K5 [get_ports {GPIO_0_tri_io[0]}]
set_property PACKAGE_PIN E6 [get_ports {GPIO_0_tri_io[1]}]
set_property PACKAGE_PIN L3 [get_ports {GPIO_0_tri_io[2]}]
set_property PACKAGE_PIN L2 [get_ports {GPIO_0_tri_io[3]}]
set_property PACKAGE_PIN A8 [get_ports {GPIO_0_tri_io[4]}]
set_property PACKAGE_PIN A9 [get_ports {GPIO_0_tri_io[5]}]
set_property PACKAGE_PIN B9 [get_ports {GPIO_0_tri_io[6]}]


set_property PULLUP true [get_ports {GPIO_0_tri_io[1]}]
set_property PULLUP true [get_ports {GPIO_0_tri_io[2]}]
set_property PULLUP true [get_ports {GPIO_0_tri_io[3]}]
set_property PULLUP true [get_ports {GPIO_0_tri_io[0]}]
set_property DRIVE 4 [get_ports {GPIO_0_tri_io[0]}]
set_property DRIVE 4 [get_ports {GPIO_0_tri_io[1]}]
set_property DRIVE 4 [get_ports {GPIO_0_tri_io[2]}]
set_property DRIVE 4 [get_ports {GPIO_0_tri_io[3]}]

#bspi

set_property PACKAGE_PIN L12 [get_ports {BSPI_O_ss_io[0]}]
set_property PACKAGE_PIN K16 [get_ports BSPI_O_io3_io]
set_property PACKAGE_PIN K15 [get_ports BSPI_O_io2_io]
set_property PACKAGE_PIN J14 [get_ports BSPI_O_io1_io]
set_property PACKAGE_PIN J13 [get_ports BSPI_O_io0_io]

set_property IOSTANDARD LVCMOS33 [get_ports BSPI_O_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports BSPI_O_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports BSPI_O_io2_io]
set_property IOSTANDARD LVCMOS33 [get_ports BSPI_O_io3_io]
set_property IOSTANDARD LVCMOS33 [get_ports {BSPI_O_ss_io[0]}]

#4线spi
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
#############SPI Configurate Setting###################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]


#ila








create_clock -period 20.000 -name clk_in -waveform {0.000 10.000} [get_ports C_SYS_CLK_I]
create_clock -period 10.000 -name sys_clk -waveform {0.000 5.000} [get_nets -hierarchical *microblaze_0_Clk*]
create_clock -period 10.000 -name dac_clk1_i -waveform {0.000 5.000} [get_ports S_DACREFCLK1_I]
create_clock -period 10.000 -name dac_clk2_i -waveform {0.000 5.000} [get_ports S_DACREFCLK2_I]

set_false_path -from [get_clocks sys_clk] -to [get_clocks dac_clk1_i]
set_false_path -from [get_clocks sys_clk] -to [get_clocks dac_clk2_i]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks dac_clk2_i]
set_false_path -from [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks dac_clk1_i]
set_false_path -from [get_clocks dac_clk1_i] -to [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks dac_clk2_i] -to [get_clocks -of_objects [get_pins bd_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT1]]

set_property PACKAGE_PIN M2 [get_ports SPI_CLK_O]
set_property PACKAGE_PIN L4 [get_ports {SPI_CS_O[0]}]
set_property PACKAGE_PIN C12 [get_ports {SPI_CS_O[1]}]
set_property PACKAGE_PIN N1 [get_ports SPI_DAT_O]
set_property PACKAGE_PIN M1 [get_ports {SPI_GPO_O[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_CS_O[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_CS_O[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_GPO_O[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CLK_O]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_DAT_O]




set_property BITSTREAM.CONFIG.M1PIN PULLDOWN [current_design]
set_property BITSTREAM.CONFIG.M2PIN PULLDOWN [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLNONE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 66 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS FALSE [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
set_property BITSTREAM.CONFIG.OVERTEMPPOWERDOWN ENABLE [current_design]

